version: '3'

services:

  frontend:
    build: frontend/
    container_name: vongline_frontend
    ports:
      - "80:80"
    volumes:
    - cert:/etc/letsencrypt/live
    
  backend:
    build: backend/
    container_name: vongline_backend
    privileged: true
    ports:
      - "8443:8443"
    volumes:
      - cert:/etc/letsencrypt/live:ro
      - vsh:/app/tmp/vsh
      - /var/run/docker.sock:/var/run/docker.sock

  compiler:
    build: compiler/
    container_name: vongline_compiler
    volumes:
      - /tmp/vongline/vch:/app/tmp/vch
      - vsh:/app/tmp/vsh:ro
    tty: true

  runtime:
    build: runtime/

volumes:
  vsh:
  cert:
