version: '2.1'

services:

  frontend:
    build: frontend/
    container_name: vongline_frontend
    ports:
      - "80:80"
  backend:
    build: backend/
    container_name: vongline_backend
    user: root
    privileged: true
    tty: true 
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - "/tmp/vongline/vsh:/app/tmp/vsh"
      - "/var/run/docker.sock:/var/run/docker.sock"


  compiler:
    build: compiler/
    container_name: vongline_compiler
    volumes:
      - "/tmp/vongline/vch:/app/tmp/vch"
    volumes_from:
      - backend
    tty: true
    stdin_open: true
  runtime:
    build: runtime/
    container_name: vongline_runtime
    volumes:
      - "/tmp/vongline/vch:/app/tmp/vch"
    tty: true
      