frontend:
  build: frontend/
  ports:
    - "80:80"
backend:
  build: backend/
  ports:
    - "3000:3000"
  volumes:
    - /tmp/java:/app/java
sandbox:
  image: java:8-jre 
  volumes_from:
    - backend
    